server:
  servlet:
    context-path: /api/auto-center

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

springdoc:
  api-docs:
    path: /api/auto-center
  swagger-ui:
    path: /swagger-ui.html
