server:
  servlet:
    context-path: /api/auto-center

h2:
  console:
    enabled: true
    path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver